"""Pydantic models -- the contract between all pipeline stages."""

from loopguard.schemas.base import SCHEMA_VERSION, SchemaVersionError, VersionedModel
from loopguard.schemas.config import (
    Arm,
    DecodingParams,
    LoopConfig,
    LoopGuardConfig,
    ModelSpec,
    PromptConfig,
    ProviderConfig,
    RateLimits,
    RetryConfig,
    RuntimeConfig,
    SemanticConfig,
    TaskConfig,
    ToolPolicy,
    ToolTag,
)
from loopguard.schemas.grade import EpisodeGrade, FailureCategory
from loopguard.schemas.manifest import JudgePin, ModelPin, RunManifest
from loopguard.schemas.task import (
    DistractorKind,
    DistractorRecord,
    Entity,
    EntityGraph,
    GoldHop,
    TaskInstance,
    TokenAccounting,
)
from loopguard.schemas.trace import (
    EpisodeFooter,
    EpisodeHeader,
    EpisodeTrace,
    StepRecord,
    TerminalReason,
    ToolCall,
)

__all__ = [
    "SCHEMA_VERSION",
    "Arm",
    "DecodingParams",
    "DistractorKind",
    "DistractorRecord",
    "Entity",
    "EntityGraph",
    "EpisodeFooter",
    "EpisodeGrade",
    "EpisodeHeader",
    "EpisodeTrace",
    "FailureCategory",
    "GoldHop",
    "JudgePin",
    "LoopConfig",
    "LoopGuardConfig",
    "ModelPin",
    "ModelSpec",
    "PromptConfig",
    "ProviderConfig",
    "RateLimits",
    "RetryConfig",
    "RunManifest",
    "RuntimeConfig",
    "SchemaVersionError",
    "SemanticConfig",
    "StepRecord",
    "TaskConfig",
    "TaskInstance",
    "TerminalReason",
    "TokenAccounting",
    "ToolCall",
    "ToolPolicy",
    "ToolTag",
    "VersionedModel",
]
